datasource:
  driverName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tee_shirt_design
  login: postgres
  password: root
  initialSize: 10
  maxActive: 7
---
jwt-token:
  secret: designShirt
  expire: 157784760000